sequenceDiagram
  participant SourceProcessor
  participant DesignExtractor
  participant UsesExtractor
  participant ModifiesExtractor
  participant ParentTExtractor
  participant FollowsTExtractor

  SourceProcessor ->>+ DesignExtractor: ExtractDesignAbstractions()

  DesignExtractor ->> UsesExtractor: Extract(deliverable)
  DesignExtractor ->> ModifiesExtractor: Extract(deliverable)
  DesignExtractor ->> ParentTExtractor: Extract(deliverable)
  DesignExtractor ->> FollowsTExtractor: Extract(deliverable)

  DesignExtractor -->>- SourceProcessor: void
