@startuml de
  skinparam shadowing false
  skinparam sequence {
    ArrowColor black
    LifeLineBorderColor grey
    LifeLineBackgroundColor lightgray
    ParticipantBorderColor lavender
    ParticipantBackgroundColor lavender
  }

  participant SourceProcessor
  participant DesignExtractor
  participant TransitiveExtractor
  participant VariableTExtractor
  participant NextExtractor

  create DesignExtractor
  SourceProcessor -> DesignExtractor: DesignExtractor(deliverable)
  SourceProcessor -> DesignExtractor: ExtractDesignAbstractions()
  activate DesignExtractor

  DesignExtractor -> TransitiveExtractor: Extract(CallsT map, \nCalledByT map, \nCalls map)
  activate TransitiveExtractor
  TransitiveExtractor --> DesignExtractor
  deactivate TransitiveExtractor
  DesignExtractor -> TransitiveExtractor: Extract(FollowsT map, \nCalledByT map, \nCalls map)
  activate TransitiveExtractor
  TransitiveExtractor --> DesignExtractor
  deactivate TransitiveExtractor
  DesignExtractor -> TransitiveExtractor: Extract(CallsT map, \nCalledByT map, \nCalls map)
  activate TransitiveExtractor
  TransitiveExtractor --> DesignExtractor
  deactivate TransitiveExtractor

  DesignExtractor -> VariableTExtractor: Extract(VariableRel::kUses)
  activate VariableTExtractor
  VariableTExtractor --> DesignExtractor
  deactivate VariableTExtractor
  DesignExtractor -> VariableTExtractor: Extract(VariableRel::kModifies)
  activate VariableTExtractor
  VariableTExtractor --> DesignExtractor
  deactivate VariableTExtractor

  DesignExtractor -> NextExtractor: Extract(deliverable)
  activate NextExtractor
  NextExtractor --> DesignExtractor
  deactivate NextExtractor

  DesignExtractor --> SourceProcessor
  deactivate DesignExtractor

@enduml
