@startuml de
  skinparam shadowing false
  skinparam sequence {
    ArrowColor black
    LifeLineBorderColor grey
    LifeLineBackgroundColor lightgray
    ParticipantBorderColor lavender
    ParticipantBackgroundColor lavender
  }

  participant SourceProcessor
  participant DesignExtractor

  create DesignExtractor
  SourceProcessor -> DesignExtractor: DesignExtractor(deliverable)
  SourceProcessor -> DesignExtractor: ExtractDesignAbstractions()
  activate DesignExtractor

  create "procedure_extractor : \nTransitiveExtractor"
  DesignExtractor -> "procedure_extractor : \nTransitiveExtractor": TransitiveExtractor<Procedure>()
  DesignExtractor -> "procedure_extractor : \nTransitiveExtractor": Extract(CallsT map, \nCalledByT map, \nCalls map)
  activate  "procedure_extractor : \nTransitiveExtractor"
   "procedure_extractor : \nTransitiveExtractor" --> DesignExtractor
  deactivate  "procedure_extractor : \nTransitiveExtractor"

  create "statement_extractor : \nTransitiveExtractor"
  DesignExtractor -> "statement_extractor : \nTransitiveExtractor": TransitiveExtractor<Statement>()
  DesignExtractor -> "statement_extractor : \nTransitiveExtractor": Extract(ParentT map, \nChildT map, \nParent map)
  activate "statement_extractor : \nTransitiveExtractor"
  "statement_extractor : \nTransitiveExtractor" --> DesignExtractor
  deactivate "statement_extractor : \nTransitiveExtractor"
  DesignExtractor -> "statement_extractor : \nTransitiveExtractor": Extract(FollowsT map, \nFollowedByT map, \nFollows map)
  activate "statement_extractor : \nTransitiveExtractor"
  "statement_extractor : \nTransitiveExtractor" --> DesignExtractor
  deactivate "statement_extractor : \nTransitiveExtractor"

  participant VariableTExtractor
  participant NextExtractor

  DesignExtractor -> VariableTExtractor: Extract(deliverable, VariableRel::kUses)
  activate VariableTExtractor
  VariableTExtractor --> DesignExtractor
  deactivate VariableTExtractor
  DesignExtractor -> VariableTExtractor: Extract(deliverable, VariableRel::kModifies)
  activate VariableTExtractor
  VariableTExtractor --> DesignExtractor
  deactivate VariableTExtractor

  DesignExtractor -> NextExtractor: Extract(deliverable)
  activate NextExtractor
  NextExtractor --> DesignExtractor
  deactivate NextExtractor

  DesignExtractor --> SourceProcessor
  deactivate DesignExtractor

@enduml
