sequenceDiagram
    autonumber
    participant P as Parser
    %% subsystem creates nodes and storing AST while the lines are being read
    %% Psystem contains statement stacks..
    participant PSub as PSubsystem
    participant Tkn as Tokenizer
    participant CGV as SyntaxValidator
    %% EntityFactory modifies necessary DSes (creates Entities, add entries into relationship, entity tables ...)
    participant EF as EntityFactory

    %% initialises the necessary data structures inside PSub, these DSes (AST, RelationshipTables, EntityTables) will be accumulated
    %% Assumption: P will check correctness while building DSes %
    P ->>+ PSub: InitDataStructures()

    %% statement here refers to the source code in between two semicolons
    %% If valid_state == false in ValidateSyntax, the loop terminates
    loop has_next_stmt && valid_syntax
        P ->>+ PSub: ProcessStatement(stmt)
        PSub ->>+ Tkn: CreateTokens(stmt)
        %% a token looks like: (<symbol>, <tokenTag>) brace_open brace_close
        Tkn -->>- PSub: list<Token> tokens

        %% We ask the validator to validate the syntax for a single statement, if there's an error at any token, it should fail early
        PSub ->>+ CGV: ValidateSyntax(vector<Token>)
        CGV -->>-PSub: bool valid_syntax

        %% create Entities:  Entity here refers to the Abstraction Entity as described by the wiki/lecture 1 slides
        PSub ->>+EF:CreateEntities(vector<Token>)
        %% This method has responsibilities such as creating necessary Entity Nodes and updating the necessary tables to reflect relationships (this is where we add info about relationships b/w lines, vars...)
        %% Entity node refers to WHILE/IF/ASSIGN... ref to
        EF-->>-PSub: Entity* entity

        PSub -->>-P:
        %% todo: handle the error handling opt code here
    end
    %% at this point, all the statements have been processed, the parser is ready for deliverables to be sent to SP
    P ->>+PSub: GetDeliverables()
    PSub -->>-P: Deliverable* deliverable
