@startuml rte
  skinparam shadowing false
  skinparam sequence {
    ArrowColor black
    LifeLineBorderColor grey
    LifeLineBackgroundColor lightgray
    ParticipantBorderColor lavender
    ParticipantBackgroundColor lavender
  }

  participant Controller
  participant PKBQueryReceiver
  participant DBManager
  participant RuntimeExtractor
  participant AffectsTExtractor
  participant NextTExtractor
  participant PKB

  create DBManager
  Controller -> DBManager: DBManager(PKB*)
  create RuntimeExtractor
  DBManager -> RuntimeExtractor: RuntimeExtractor(PKB*)

  PKBQueryReceiver -> DBManager ++: GetRelationship(RelRef, string)
    alt runtime rs
      DBManager -> RuntimeExtractor ++: GetAffectsT(string)
        RuntimeExtractor -> PKB ++: GetDS
        PKB -> RuntimeExtractor --: DS
        RuntimeExtractor -> AffectsTExtractor ++: GetAffectsT(DS..., string)
      AffectsTExtractor -> RuntimeExtractor ++: GetNextT(string)
          RuntimeExtractor -> NextTExtractor ++: GetNextT(DS..., string)
          NextTExtractor --> RuntimeExtractor --: vector<Entity*>
      RuntimeExtractor --> AffectsTExtractor --: vector<Entity*>
        AffectsTExtractor --> RuntimeExtractor --: vector<Entity*>
      RuntimeExtractor --> DBManager --: vector<Entity*>
    else pkb rs
      DBManager -> PKB ++: GetRelationship(RelRef, string)
      PKB --> DBManager --: vector<Entity*>
    end
  DBManager --> PKBQueryReceiver --: vector<Entity*>

@enduml
