@startuml rte
  skinparam shadowing false
  skinparam sequence {
    ArrowColor black
    LifeLineBorderColor grey
    LifeLineBackgroundColor lightgray
    ParticipantBorderColor lavender
    ParticipantBackgroundColor lavender
  }

  participant DBManager
  participant RuntimeExtractor
  participant AffectsExtractor
  participant AffectsTExtractor

  create RuntimeExtractor
  DBManager -> RuntimeExtractor: RuntimeExtractor(PKB*)

  DBManager -> RuntimeExtractor ++: GetRelationship(PKBRelRef::kAffectsT, string)
    RuntimeExtractor -> AffectsTExtractor ++: GetRelationship(RelDirection::kForward, string)
      AffectsTExtractor -> RuntimeExtractor ++: GetRelationship(PKBRelRef::kAffects, string)
        RuntimeExtractor -> AffectsExtractor ++: GetRelationship(RelDirection::kForward, string)
        AffectsExtractor --> RuntimeExtractor --: vector<Entity*>
      RuntimeExtractor --> AffectsTExtractor --: vector<Entity*>
    AffectsTExtractor --> RuntimeExtractor --: vector<Entity*>
  RuntimeExtractor --> DBManager --: vector<Entity*>

@enduml
