@startuml
<Style>
activityDiagram {
  BackgroundColor lavender
  BorderColor lavender
  FontName arial
  FontSize 13
LineColor Black
}
document {
   BackgroundColor transparent
}
</style>
skinparam sequence {
  ArrowColor black
  BorderColor black
  ActivityBorderColor black
}

@startuml
start

repeat
  :choose an unvisited target synonym;
  #khaki:perform BFS traversal subroutine \n from target synonym;
repeat while (has unvisited target synonyms?) is (yes)
->no;
repeat
  :choose an unvisited clause;
if (clause has at least 1 synonym) is (yes) then
  -[#black]->
  #khaki:perform BFS traversal subroutine \n from any one of its synonyms;
else
  -[#black,dotted]->
  :add clause to its own group;
endif
-[#black]->
repeat while (has unvisited synonyms?) is (yes)
stop
@enduml