classDiagram
    class StatementNumber {
        -num:int
    }

    class LineNumber {
        -num:int
    }
        
    class ProcedureName {
        -name:string
    }

    class VariableName {
        -name:string
    }

    class Constant {
        -digits:int
    }

    class AssignmentExpression {
        PLACEHOLDER
    }
    
    class ConditionalExpression {
        -expression:string
    }
