stateDiagram-v2

Block(1,2) --> Block_while_cond(3,3)

Block_while_cond(3,3) --> Block_while_cond(4,4)
note left of Block_while_cond(3,3) : #4 is in this cluster (#3,#11)\n so recurse into the next cluster(#12, #14).

Block_while_cond(4,4) --> Block_while_cond(3,3)
Block_while_cond(3,3) --> Block_IfCond(12,12)

Block_while_cond(4,4) --> Block(5,6)

Block(5,6) --> Block_if_cond(7,7)

Block_if_cond(7,7) --> Block(8,8)
Block_if_cond(7,7) --> Block(9,10)
Block(8,8) --> Block(11,11)
Block(9,10) --> Block(11,11)
Block(11,11) --> Block_while_cond(4,4)
Block(11,11) --> Block_IfCond(12,12)
note right of Block_IfCond(12,12) : Continue traversal until leaf node is reached

Block_IfCond(12,12) --> Block(13,13)
Block_IfCond(12,12) --> Block(14,14)
Block(13,13) --> Block(15,15)
note left of Block(14,14) : Return list with #15 to the recursive function
Block(14,14) --> Block(15,15)
note right of Block(15,15) : Return empty list to the recursive function

