gantt
    todayMarker off
    title Iteration 2
    dateFormat  YYYY-MM-DD
    section SourceProc
    Parse multiple procedures       :a1, 2021-09-27, 7d
    CFG blocks                      :a1, 2021-10-04, 4d
    CFG clusters                    :a1, 2021-10-08, 7d
    Calls/Calls*                    :a1, 2021-10-04, 7d
    Next                            :a1, 2021-10-14, 4d
    section PKB
    Refactorization of API          :a1, 2021-10-03, 14d
    Optimize data structures        :a1, 2021-10-03, 14d
    section QueryProc
    Refactorization of Evaluator    :a1, 2021-09-29, 14d
    Refactorization of Processor    :a1, 2021-09-29, 14d
    Creating design patterns        :a1, 2021-10-03, 10d
    Query Extraction (full spa)     :a1, 2021-10-11, 7d
    Support new return types        :a1, 2021-10-13, 3d
    section Testing
    Unit Testing                    :a1, 2021-09-27, 20d
    Integration testing             :a1, 2021-10-07, 11d
    System testing                  :a1, 2021-10-11, 7d
    section Docs
    Documentation                   :a1, 2021-10-11, 7d
