gantt
    title CS3203 Gantt Chart
    dateFormat  YYYY-MM-DD
    section SourceProc
    Tokenization                                        :a1, 2021-08-30, 7d
    Syntax Validation                                   :a1, 2021-08-30, 14d
    Syntax Validation                                   :a1, 2021-09-16, 3d
    Entity Extraction                                   :a1, 2021-08-30, 7d
    Non-Transitive Relationship Extraction              :a1, 2021-09-02, 7d
    Transitive Relationship Extraction                  :a1, 2021-09-06, 7d
    section PKB
    PKB Population (Entity)                             :a1, 2021-08-30, 7d
    PKB Population (Non-transitive RS)                  :a1, 2021-09-02, 7d
    PKB Population (Transitive RS)                      :a1, 2021-09-02, 10d
    PKB Retrieval                                       :a1, 2021-08-30, 14d
    section QueryProc
    Query Extraction                                    :a1, 2021-08-30, 10d
    Query Evaluation (Non-transitive such-that)         :a1, 2021-08-30, 10d
    Query Evaluation (Transitive such-that)             :a1, 2021-09-06, 7d
    Support pattern query                               :a1, 2021-09-06, 7d
    Support multiple such-that/pattern clauses          :a1, 2021-09-09, 3d
    Query Projection                                    :a1, 2021-09-06, 7d
    section Testing
    Unit testing                                        :a1, 2021-08-30, 10d
    Integration testing                                 :a1, 2021-09-06, 10d
    System testing                                      :a1, 2021-09-13, 7d
    section Debug
    Debugging                                           :a1, 2021-09-09, 10d
    section Docs
    Documentation                                       :a1, 2021-08-30, 3d
    Documentation                                       :a1, 2021-09-09, 10d
