name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
     - '**' #run for all PR

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  working-directory: ${{github.workspace}}/Team35/Code35

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Check Path
      run: echo ${{env.working-directory}}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -S ${{env.working-directory}} -B ${{env.working-directory}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build SPA
      # Build your program with the given configuration
      run: cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target spa
      
    - name: Build Unit Test
      run: cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target unit_testing

    - name: Run Unit Test
      #Running Catch2 natively on terminal
      run: |
        cd ${{env.working-directory}}/build/src/unit_testing/
        ./unit_testing

    - name: Build Integration Test
      run: cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target integration_testing

    - name: Run Integration Test
      run: |
        cp -r ${{env.working-directory}}/tests/integration_test_files ${{env.working-directory}}/build/src/integration_testing/
        cd ${{env.working-directory}}/build/src/integration_testing/
        ./integration_testing
  
    - name: Build AutoTester # GUI is excluded
      run:  cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target autotester
    
    - name: Run AutoTester 
      run: | 
        cp -r ${{env.working-directory}}/../Test35 ${{env.working-directory}}/build/src/autotester
        cd ${{env.working-directory}}/build/src/autotester/Test35
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
        
    - uses: actions/upload-artifact@v2
      with: 
        name: output_final
        path: ${{env.working-directory}}/build/src/autotester/Test35/output_final.zip

    - name: Build All # Take all previous build and build autotester_gui for completeness
      run: cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target all
