name: CMake_Master

# Master is a build all and check. 
# It will not create any artifact because errors should be fixed in PR. 
on:
  push:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  working-directory: ${{github.workspace}}/Team35/Code35

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Check Path
      run: echo ${{env.working-directory}}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -S ${{env.working-directory}} -B ${{env.working-directory}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build all
      run: cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target all -- -j 8

    - name: Run Unit Test
      #Running Catch2 natively on terminal
      run: |
        cd ${{env.working-directory}}/build/src/unit_testing/
        ./unit_testing

    - name: Run Integration Test
      run: |
        cp -r ${{env.working-directory}}/tests/integration_test_files ${{env.working-directory}}/build/src/integration_testing/
        cd ${{env.working-directory}}/build/src/integration_testing/
        ./integration_testing

      
    - name: Run AutoTester - Throws
      run: | 
        cp -r ${{github.workspace}}/Team35/Tests35 ${{env.working-directory}}/build/src/autotester
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/throw
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
        
    - name: Run AutoTester - PQL_Single
      run: | 
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/pql_single
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
        
    - name: Run AutoTester - PQL_Multiple
      run: | 
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/pql_multiple
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
    
    - name: Run AutoTester - Basic
      run: | 
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/basic
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
    
    - name: Run AutoTester - Advanced
      run: | 
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/adv
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
        
    - name: Run AutoTester - Timed
      run: | 
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/timed
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
