name: CMake_PR

on:
  pull_request:
    branches:
     - '**' #run for all PR

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  working-directory: ${{github.workspace}}/Team35/Code35

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Check Path
      run: echo ${{env.working-directory}}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -S ${{env.working-directory}} -B ${{env.working-directory}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build SPA
      # Build your program with the given configuration
      run: cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target spa -- -j 8
      
    - name: Build Unit Test
      run: cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target unit_testing -- -j 8

    - name: Run Unit Test
      #Running Catch2 natively on terminal
      run: |
        cd ${{env.working-directory}}/build/src/unit_testing/
        ./unit_testing

    - name: Build Integration Test
      run: cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target integration_testing -- -j 8

    - name: Run Integration Test
      run: |
        cp -r ${{env.working-directory}}/tests/integration_test_files ${{env.working-directory}}/build/src/integration_testing/
        cd ${{env.working-directory}}/build/src/integration_testing/
        ./integration_testing
  
    - name: Build AutoTester # GUI is excluded
      run:  cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target autotester -- -j 8
    
    - name: Run AutoTester - Basic
      run: | 
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/basic
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
    
    - name: Run AutoTester - Advanced
      run: | 
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/adv
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
        
    - name: Run AutoTester - Throws
      run: | 
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/throw
        chmod +x ./run_autotester_suite.sh
        ./run_autotester_suite.sh
        
    - name: Zip result logs
      run: | 
        cd ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib
        zip -v basic.zip basic/log_*.txt basic/output_*.xml basic/Team35_SPA_*.log analysis.xsl
        zip -v adv.zip adv/log_*.txt adv/output_*.xml adv/Team35_SPA_*.log analysis.xsl
        
    - uses: actions/upload-artifact@v2
      with: 
        name: output_final
        path: |
            ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/basic.zip 
            ${{env.working-directory}}/build/src/autotester/Tests35/simple_lib/adv.zip 

    - name: Build All # Take all previous build and build autotester_gui for completeness
      run: cmake --build ${{env.working-directory}}/build --config ${{env.BUILD_TYPE}} --target all
